services:
  - type: web
    name: pronunciation-evaluation
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
